<a href="https://colab.research.google.com/github/sejal-oli7/python/blob/main/%20python%20/%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy (NUmerical Python)
- python library used to working with arrays
- it also uses linear algebra, fourier transform, and matrices operations
- Why is it diff than list?
 - its because its speed, nunpy arrays are stored at one continuous place in memory , so process can be very efficient and fast

In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


### Creating an arrays using numpy

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Create a NUmpy ndarray Objects

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
## 0-D Arrays
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
## 1-D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
## 2-D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
## 3-D array
arr = np.array ([[[1,2,3,], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check Number of Dimensions in an Numpy Array?

In [12]:
# CHeck NUmber of Dimensions in an Numpy Array?
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
# cretae an array of 5 dim and verify its dim

import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Access Array Elements


In [14]:
import numpy as np
arr = np.array([1,2,3,3])
print(arr[2])

3


In [15]:
#3ed and 4th element add
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


## Acessing 2-D array

In [18]:
import numpy as np
arr = np.array([[1,2,3,4,5] ,[6,7,8,9,10]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
print(arr[0, 2])
print(arr[1, 0])
print(arr[1, 4])

3
6
10
